### ISSUE TITLE
Works on Mac?

### ISSUE THREAD

**Issue by ohjay73** [UlricusR/ulricusr.github.io#1]
Comments say this app will work on  Mac but Requires macOS 11.0 or later and a Mac with Apple M1 chip or later. I'm running a Macbook pro and the app will not allow me to install from the appstore.

**Comment by UlricusR** [comment]
Hi, which app are you talking about? The issue you opened is in the repository of my homepage... EasyFPU?

**Comment by ohjay73** [comment]
I can get the app to open and install on an ios and android handset.. but
would like to have it on my MacBook for my wife. The appstore says the app
is not compatible with the MacBook pro and therefore won't install.

**Comment by ohjay73** [comment]
yes.. easyfpu.. sry for not being clear

**Comment by UlricusR** [comment]
I looked into this. If you have a MacBook with an Apple (no Intel) chip, it can be run on the MacBook, otherwise unfortunately not without me adapting it.

You can check this by clicking on the little Apple icon in the top left corner and choosing "About this Mac".

I will check later if I can easily make the app available for Intel chip MacBooks or if this takes a lot of rework. I'll let you know.

**Comment by ohjay73** [comment]
Yup.. Intel..  core i7.. well that's unfortunate

**Comment by UlricusR** [comment]
Unfortunately it’s not an easy thing to make the app available for all Macs - some libraries I use are only available for iOS.Am 22.01.2023 um 23:41 schrieb ohjay73 ***@***.***>:﻿
Yup.. Intel..  core i7.. well that's unfortunate
